node:
  server01:
    ports:
      eth0:
        dhcp:
      eth1:
        ip: 10.0.10.10/24
        gw: 10.0.10.1
  server02:
    ports:
      eth0:
        dhcp:
      eth1:
        ip: 10.0.20.20/24
        gw: 10.0.20.1
