---

- name: Verify Minimum Software Version
  assert:
    that: "{{ansible_lsb.release is version_compare('4.2.0', '>=') }}"
    msg: >
      "Cumulus Linux version must be 4.2.0 or later.
      Version {{ansible_lsb.release}} detected"
      
- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes
  notify: restart frr

- name: Copy interfaces configuration
  copy:
    src: configurations/{{inventory_hostname}}_interfaces.txt
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking

- name: Copy FRR configuration
  copy:
    src: configurations/{{inventory_hostname}}_frr.txt
    dest: /etc/frr/frr.conf
    backup: yes
  notify: reload frr

- name: Flush Handlers, best practice
  meta: flush_handlers