# - hosts: server03
#   become: true
#   roles:
#     - servers

- hosts: sonicbonus
  become: true
  roles:
    - sonic
    - netq-sonic
# - hosts: cumulusswitches
#   become: true
#   roles:
#     - cumulus
#     - netq-cumulus
