---
# - name: Sonic Cleanup Commands
#   command: "{{ item }}"
#   with_items:
#     - sudo config interface ip remove Ethernet0 10.0.0.0/31
#     - sudo config interface ip remove Ethernet4 10.0.0.2/31
#     - sudo config interface ip remove Ethernet8 10.0.0.4/31
#     - sudo config interface ip remove Ethernet12 10.0.0.6/31
#     - sudo config bgp remove neighbor 10.0.0.1
#     - sudo config bgp remove neighbor 10.0.0.3
#     - sudo config bgp remove neighbor 10.0.0.5
#     - sudo config bgp remove neighbor 10.0.0.7
#     - sudo config save -y

- name: Restore config_db
  copy: src=./configurations/{{inventory_hostname}}_config_db.json dest=/etc/sonic/config_db.json
  notify: reload sonic config

- name: Set eth[1-9] MTU to 9238
  shell: |
    for i in $(ip link | grep eth[1-9] | awk -F':' '{print $2}'); do
      ip link set mtu 9238 $i
    done
  args:
    executable: /bin/bash

- name: Check for ebtables.filter
  stat: path=/etc/ebtables.filter
  register: ebtables_stat

- name: Disable default ebtables DROP rules
  command: mv /etc/ebtables.filter /etc/ebtables.filter.disabled
  when: ebtables_stat.stat.exists
  notify: flush ebtables

- name: Flush Handlers, best practice
  meta: flush_handlers
