---

- name: Sonic Cleanup Commands
  command: "{{ item }}"
  with_items:
    - sudo config interface ip remove Ethernet0 10.0.0.0/31
    - sudo config interface ip remove Ethernet0 10.0.0.2/31
    - sudo config interface ip remove Ethernet0 10.0.0.4/31
    - sudo config interface ip remove Ethernet0 10.0.0.6/31
    - sudo config bgp remove neighbor 10.0.0.1
    - sudo config bgp remove neighbor 10.0.0.3
    - sudo config bgp remove neighbor 10.0.0.5
    - sudo config bgp remove neighbor 10.0.0.7
    - sudo config save -y

- name: Flush Handlers, best practice
  meta: flush_handlers
